name: Go Tracer Release
on:
  pull_request:
    branches:
      - release
jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    steps:
    - run: echo "This echo only exists in the PR"
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
