name: Go Tracer Release
on:
  pull_request:
    branches:
      - release
jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - run: |
        echo "Github repo info: ${{ github.repository }}"
        ls -la .
        git log -1 || exit 0