name: Go Tracer Release
on:
  pull_request:
    branches:
      - release
jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    steps:
    - run: |
        apt update
        echo "This echo only exists in the PR"
        ls -la .
        exit 1

