name: Go Tracer Release
on:
  pull_request_target:
    branches:
      - release
  # pull_request:
  #   types: [opened, synchronize, reopened]
jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello World!"
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
