name: Go Tracer Release
# on:
#   pull_request:
#     branches:
#       - release

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'The package name of the instrumented package. Eg: instagorm'
        required: true
        default: 'instagin'
        type: choice
        options:
        - instaredis
        - instapgx
        - instagorm

jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - run: |
        echo "Releasing $INSTANA_PACKAGE_NAME"
        git log -1 --name-only --oneline --pretty=format:

      env:
        INSTANA_PACKAGE_NAME: ${{ inputs.packageName }}
