name: Update all instrumentations PR

on:
  workflow_run:
    workflows: ["Go Tracer Release"]
    types: [completed]

jobs:
  updade_instrumentations:
    name: Update instrumentations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout repo
      with:
        fetch-depth: 0
    - name: Check if is core
      run: |
        CORE_TAG=$(git tag -l "v1.*" | sort -V | tail -n1)
        echo "New core version is $CORE_TAG"

        #!/bin/bash

        EXCLUDED_DIRS="\/.*\/example"

        # List of instrumentation folders
        LIB_LIST=$(find ./instrumentation -name go.mod -exec dirname {} \; | grep -E -v "$EXCLUDED_DIRS")

        echo "updating main branch before creating branch"
        git pull
        git log -1

        # Updates all instrumentations to use the @latest version of the core module
        for lib in $LIB_LIST
          do sed -i "s|github\.com\/instana\/go-sensor v.*|github\.com\/instana\/go-sensor ${CORE_TAG}|" "$lib"/go.mod
        done

        git config user.name "IBM/Instana/Team Go"
        git config user.email "github-actions@github.com"


        git checkout -b update-instrumentations-core-"$CORE_TAG" || git checkout update-instrumentations-core-"$CORE_TAG"

        echo "rebase main"
        git rebase main

        git add .
        git commit -m "Updating instrumentations to core module $CORE_TAG"
        git push origin update-instrumentations-core-"$CORE_TAG"

        gh pr create update-instrumentations-core-"$CORE_TAG"

      env:
        GH_TOKEN: ${{ github.token }}
